### ISSUE TITLE
[Errno 13] Permission denied

### ISSUE THREAD

**Issue by ahslaz** [LagoLunatic/wwrando#140]
Randomization failed with error:
[Errno 13] Permission denied

Software tries to locate nonexistent locations and files on my computer (like C:\Users\Dbe\Desktop\Wind Waker\wwrando\...) several times and ends the traceback with "PermissionError: [Errno 13] Permission denied"
Couldn't find any solution to this problem online.

**Comment by ahslaz** [comment]
This is the log I get

Randomization failed with error:
[Errno 13] Permission denied

Traceback (most recent call last):
  File "C:\Users\Dbe\Desktop\Wind Waker\wwrando\wwr_ui\randomizer_window.py", line 997, in run
  File "C:\Users\Dbe\Desktop\Wind Waker\wwrando\randomizer.py", line 308, in randomize
  File "C:\Users\Dbe\Desktop\Wind Waker\wwrando\randomizer.py", line 378, in apply_necessary_tweaks
  File "C:\Users\Dbe\Desktop\Wind Waker\wwrando\tweaks.py", line 222, in fix_deku_leaf_model
  File "C:\Users\Dbe\Desktop\Wind Waker\wwrando\randomizer.py", line 536, in get_arc
  File "C:\Users\Dbe\Desktop\Wind Waker\wwrando\wwlib\gcm.py", line 107, in read_file_data
  File "C:\Users\Dbe\Desktop\Wind Waker\wwrando\fs_helpers.py", line 14, in read_bytes
PermissionError: [Errno 13] Permission denied

**Comment by LagoLunatic** [comment]
>Software tries to locate nonexistent locations and files on my computer (like C:\Users\Dbe\Desktop\Wind Waker\wwrando...)

It's not trying to locate those files. Those are the source code files on the computer the executable was built on (mine). It's normal for those paths to appear in error messages.

It's having some kind of issue reading your vanilla wind waker ISO partway through the randomization. I've never heard of this issue before, but the only thing I could think of causing this issue is if some other program is accessing your ISO at the same time as the randomizer. Like for example, Dolphin, or a second instance of the randomizer running at the same time, or something like that. Or perhaps you moved the ISO to a different path on your computer in the middle of randomization so it couldn't find it anymore.

**Comment by ahslaz** [comment]
I got a new clean iso file, put it and chose the output folder in the randomizer on a freshly formatted USB drive. It fixed the issue.
