### ISSUE TITLE
PySide2 Not Found

### ISSUE THREAD

**Issue by yulayula16** [LagoLunatic/wwrando#178]
PySide2 isn't able to be downloaded as listed in the `requirements.txt` file because it returns Error 404 Not Found.

```PYTHON
Collecting PySide2==5.14.1
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://packagecloud.io/JonasGroeger/soundnode/pypi/simple/pyside2/
```
this would need to corrected to instead look for it at a different source, because that version you're looking for doesn't exist anymore at that URL from JonasGroeger's repo which hasn't been updated in 3 years. You'll maybe want to change this to use PySide2 version `5.13.1` or `5.14.2`

**Comment by LagoLunatic** [comment]
It works fine for me:
```
Collecting PySide2==5.14.1
  Downloading PySide2-5.14.1-5.14.1-cp35.cp36.cp37.cp38-none-win_amd64.whl (135.9 MB)
     |████████████████████████████████| 135.9 MB 3.2 MB/s
```

I have no idea who JonasGroeger is or what you mean with a repo not being updated in 3 years, PySide2 didn't even exist 3 years ago.

I updated the requirement to 5.14.2 since it was easy, can you check if this fixes the issue for you?

**Comment by LagoLunatic** [comment]
Closing since OP isn't responding. Was probably some kind of cache issue on OP's computer.
