### ISSUE TITLE
Module import error when running built executable

### ISSUE THREAD

**Issue by JohnDevlopment** [LagoLunatic/wwrando#305]
I made a virtual environment for Python 3.10.7, and I installed every dependency under it.

I ran this command after installing each dependency:

```sh
python -m PyInstaller wwrando.spec
```
And this is the output that I got:

```
114 INFO: PyInstaller: 5.6.2
114 INFO: Python: 3.10.7
115 INFO: Platform: Linux-5.4.0-135-generic-x86_64-with-glibc2.27
117 INFO: UPX is not available.
('asm/free_space_start_offsets.txt', 'asm')
('asm/custom_symbols.txt', 'asm')
('asm/d_a_switch_op.rel', 'asm')
('asm/patch_diffs/misc_rando_features_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/remove_music_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/make_items_progressive_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/disable_tingle_bombs_on_tingle_chests_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/tingle_chests_without_tuner_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/flexible_item_locations_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/b_button_skips_text_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/swift_sail_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/reveal_sea_chart_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/make_game_nonlinear_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/map_select_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/test_room_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/custom_funcs_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/swordless_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/remove_cutscenes_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/invert_camera_x_axis_diff.txt', 'asm/patch_diffs')
('asm/patch_diffs/fix_vanilla_bugs_diff.txt', 'asm/patch_diffs')
('assets/key bag.png', 'assets')
('assets/Vscroll.arc', 'assets')
('assets/memory card banner.png', 'assets')
('assets/title.png', 'assets')
('assets/blank.thp', 'assets')
('assets/icon.ico', 'assets')
('assets/subtitle.png', 'assets')
('assets/memory card icon.png', 'assets')
('assets/swift sail item get texture.png', 'assets')
('assets/swift sail texture.png', 'assets')
('assets/swift sail icon.png', 'assets')
('assets/link_metadata.txt', 'assets')
('assets/banner.png', 'assets')
('assets/link_preview/preview_hero_Belt Buckle.png', 'assets/link_preview')
('assets/link_preview/preview_casual_Armbands.png', 'assets/link_preview')
('assets/link_preview/preview_hero_Boots.png', 'assets/link_preview')
('assets/link_preview/preview_casual_Shoe Soles.png', 'assets/link_preview')
('assets/link_preview/preview_hero_Mouth.png', 'assets/link_preview')
('assets/link_preview/preview_hero_Hair.png', 'assets/link_preview')
('assets/link_preview/preview_casual.png', 'assets/link_preview')
('assets/link_preview/preview_casual_Mouth.png', 'assets/link_preview')
('assets/link_preview/preview_casual_Skin.png', 'assets/link_preview')
('assets/link_preview/preview_casual_Shirt Emblem.png', 'assets/link_preview')
('assets/link_preview/preview_casual_Shirt.png', 'assets/link_preview')
('assets/link_preview/preview_hero_Undershirt.png', 'assets/link_preview')
('assets/link_preview/preview_casual_Pants.png', 'assets/link_preview')
('assets/link_preview/preview_hero_Eyes.png', 'assets/link_preview')
('assets/link_preview/preview_hero_Skin.png', 'assets/link_preview')
('assets/link_preview/preview_hero_Sclera.png', 'assets/link_preview')
('assets/link_preview/preview_casual_Shoes.png', 'assets/link_preview')
('assets/link_preview/preview_hero.png', 'assets/link_preview')
('assets/link_preview/preview_hero_Pants.png', 'assets/link_preview')
('assets/link_preview/preview_hero_Belt.png', 'assets/link_preview')
('assets/link_preview/preview_casual_Eyes.png', 'assets/link_preview')
('assets/link_preview/preview_casual_Sclera.png', 'assets/link_preview')
('assets/link_preview/preview_hero_Shirt.png', 'assets/link_preview')
('assets/link_preview/preview_casual_Hair.png', 'assets/link_preview')
('assets/link_color_masks/casual_Shirt Emblem.png', 'assets/link_color_masks')
('assets/link_color_masks/hero_Shirt.png', 'assets/link_color_masks')
('assets/link_color_masks/casual_Shirt.png', 'assets/link_color_masks')
('assets/link_color_masks/casual_Skin.png', 'assets/link_color_masks')
('assets/link_color_masks/hero_Skin.png', 'assets/link_color_masks')
('assets/link_color_masks/hero_Belt Buckle.png', 'assets/link_color_masks')
('assets/link_color_masks/hero_Mouth.png', 'assets/link_color_masks')
('assets/link_color_masks/casual_Armbands.png', 'assets/link_color_masks')
('assets/link_color_masks/casual_Shoes.png', 'assets/link_color_masks')
('assets/link_color_masks/hitomi_casual_Sclera.png', 'assets/link_color_masks')
('assets/link_color_masks/casual_Hair.png', 'assets/link_color_masks')
('assets/link_color_masks/hero_Hair.png', 'assets/link_color_masks')
('assets/link_color_masks/hero_Undershirt.png', 'assets/link_color_masks')
('assets/link_color_masks/hero_Belt.png', 'assets/link_color_masks')
('assets/link_color_masks/hitomi_hero_Sclera.png', 'assets/link_color_masks')
('assets/link_color_masks/casual_Mouth.png', 'assets/link_color_masks')
('assets/link_color_masks/hitomi_hero_Eyes.png', 'assets/link_color_masks')
('assets/link_color_masks/hero_Pants.png', 'assets/link_color_masks')
('assets/link_color_masks/casual_Shoe Soles.png', 'assets/link_color_masks')
('assets/link_color_masks/hitomi_casual_Eyes.png', 'assets/link_color_masks')
('assets/link_color_masks/casual_Pants.png', 'assets/link_color_masks')
('assets/link_color_masks/hero_Boots.png', 'assets/link_color_masks')
('assets/link_color_masks/mouths/mouthS3TC.7_Skin.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.8_Mouth.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.1_Skin.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.9_Skin.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.6_Mouth.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.3_Skin.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.1_Mouth.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.5_Mouth.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.2_Skin.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.6_Skin.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.5_Skin.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.9_Mouth.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.7_Mouth.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.4_Skin.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.8_Skin.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.2_Mouth.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.4_Mouth.png', 'assets/link_color_masks/mouths')
('assets/link_color_masks/mouths/mouthS3TC.3_Mouth.png', 'assets/link_color_masks/mouths')
('data/island_name_hints.txt', 'data')
('data/progress_item_hints.txt', 'data')
('data/items_without_field_models.txt', 'data')
('data/stage_names.txt', 'data')
('data/enemy_types.txt', 'data')
('data/item_resource_icon_name_pointers.txt', 'data')
('data/actor_info.txt', 'data')
('data/item_resource_arc_name_pointers.txt', 'data')
('data/island_names.txt', 'data')
('data/actor_parameters.txt', 'data')
('data/item_names.txt', 'data')
('data/palette_randomizable_files.txt', 'data')
('logic/enemy_locations.txt', 'logic')
('logic/item_locations.txt', 'logic')
('logic/macros.txt', 'logic')
('seedgen/adjectives.txt', 'seedgen')
('seedgen/names.txt', 'seedgen')
('seedgen/nouns.txt', 'seedgen')
('version.txt', '.')
124 INFO: Extending PYTHONPATH with paths
['/home/user/install/wwrando-1.9.0']
335 INFO: Will encrypt Python bytecode with provided cipher key
336 INFO: checking Analysis
356 INFO: Building because hiddenimports changed
356 INFO: Initializing module dependency graph...
357 INFO: Caching module graph hooks...
367 INFO: Analyzing base_library.zip ...
/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py:20: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py:20: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py:20: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
<frozen importlib._bootstrap_external>:1523: DeprecationWarning: FileFinder.find_loader() is deprecated and slated for removal in Python 3.12; use find_spec() instead
1104 INFO: Loading module hook 'hook-heapq.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
1393 INFO: Loading module hook 'hook-encodings.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py:20: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
3441 INFO: Loading module hook 'hook-pickle.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
6118 INFO: Caching module dependency graph...
6266 INFO: running Analysis Analysis-00.toc
6273 INFO: Analyzing /home/user/install/wwrando-1.9.0/wwrando.py
<frozen importlib._bootstrap_external>:1523: DeprecationWarning: FileFinder.find_loader() is deprecated and slated for removal in Python 3.12; use find_spec() instead
6286 INFO: Loading module hook 'hook-PySide2.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
6635 INFO: Processing pre-find module path hook distutils from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
6906 INFO: Loading module hook 'hook-distutils.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
7488 INFO: Loading module hook 'hook-PIL.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
7611 INFO: Loading module hook 'hook-PIL.Image.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py:20: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
8452 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
/home/user/install/wwrando-1.9.0/asm/disassemble.py:304: DeprecationWarning: invalid escape sequence '\s'
  load_or_store_match = re.search(r"^.+ \t(?:" + "|".join(ALL_LOAD_OR_STORE_OPCODES) + ")\s+[rf]\d+,(-?\d+)\((r\d+)\)$", line, re.IGNORECASE)
9219 INFO: Analyzing hidden import 'tinyaes'
9219 INFO: Processing module hooks...
9220 INFO: Loading module hook 'hook-PySide2.QtNetwork.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
9322 INFO: Loading module hook 'hook-PySide2.QtGui.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
<frozen importlib._bootstrap_external>:1523: DeprecationWarning: FileFinder.find_loader() is deprecated and slated for removal in Python 3.12; use find_spec() instead
9681 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
9727 INFO: Loading module hook 'hook-PySide2.QtWidgets.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
<frozen importlib._bootstrap_external>:1523: DeprecationWarning: FileFinder.find_loader() is deprecated and slated for removal in Python 3.12; use find_spec() instead
9900 INFO: Loading module hook 'hook-setuptools.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py:20: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py:20: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
11051 INFO: Loading module hook 'hook-distutils.util.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
11095 INFO: Loading module hook 'hook-sysconfig.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
11468 INFO: Loading module hook 'hook-pkg_resources.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py:20: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
11991 INFO: Loading module hook 'hook-platform.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
12037 INFO: Loading module hook 'hook-xml.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
12772 INFO: Loading module hook 'hook-PySide2.QtCore.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
<frozen importlib._bootstrap_external>:1523: DeprecationWarning: FileFinder.find_loader() is deprecated and slated for removal in Python 3.12; use find_spec() instead
13552 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
14000 INFO: Loading module hook 'hook-setuptools.msvc.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
15010 INFO: Loading module hook 'hook-difflib.py' from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks'...
16198 INFO: Processing pre-safe import module hook win32com from '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
16966 INFO: checking Tree
16967 INFO: Building because root changed
16967 INFO: Building Tree Tree-00.toc
16967 INFO: checking Tree
16967 INFO: Building because root changed
16967 INFO: Building Tree Tree-01.toc
16968 INFO: Looking for ctypes DLLs
16996 INFO: Analyzing run-time hooks ...
17002 INFO: Including run-time hook '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_subprocess.py'
17003 INFO: Including run-time hook '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
17004 INFO: Including run-time hook '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
17007 INFO: Including run-time hook '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_setuptools.py'
17008 INFO: Including run-time hook '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
17010 INFO: Including run-time hook '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
17016 INFO: Including run-time hook '/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pyside2.py'
17028 INFO: Looking for dynamic libraries
/home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py:20: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
1641 WARNING: Cannot find libwebp-b246aa5a.so.7.1.5 (needed by /home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PIL/../Pillow.libs/libwebpdemux-ac83b303.so.2.0.11)
1654 WARNING: Cannot find libwebp-b246aa5a.so.7.1.5 (needed by /home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PIL/../Pillow.libs/libwebpmux-502c7428.so.3.0.10)
1676 WARNING: Cannot find liblzma-816f5b19.so.5.2.7 (needed by /home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PIL/../Pillow.libs/libtiff-3a0dc242.so.5.8.0)
1676 WARNING: Cannot find libjpeg-b1f3a3b7.so.62.3.0 (needed by /home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PIL/../Pillow.libs/libtiff-3a0dc242.so.5.8.0)
1687 WARNING: Cannot find libXau-00ec42fe.so.6.0.0 (needed by /home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PIL/../Pillow.libs/libxcb-421a6fdb.so.1.1.0)
18913 INFO: Looking for eggs
18913 INFO: Python library not in binary dependencies. Doing additional searching...
18932 INFO: Using Python library /usr/local/lib/libpython3.10.so.1.0
18943 INFO: Warnings written to /home/user/install/wwrando-1.9.0/build/wwrando/warn-wwrando.txt
19013 INFO: Graph cross-reference written to /home/user/install/wwrando-1.9.0/build/wwrando/xref-wwrando.html
19040 INFO: Appending 'datas' from .spec
19045 INFO: checking PYZ
19052 INFO: Building because toc changed
19052 INFO: Building PYZ (ZlibArchive) /home/user/install/wwrando-1.9.0/build/wwrando/PYZ-00.pyz
19835 INFO: Building PYZ (ZlibArchive) /home/user/install/wwrando-1.9.0/build/wwrando/PYZ-00.pyz completed successfully.
19853 INFO: checking PKG
19857 INFO: Building because toc changed
19857 INFO: Building PKG (CArchive) Wind Waker Randomizer 1.9.0_64bit.pkg
45177 INFO: Building PKG (CArchive) Wind Waker Randomizer 1.9.0_64bit.pkg completed successfully.
45194 INFO: Bootloader /home/user/install/wwrando-1.9.0/.env/lib/python3.10/site-packages/PyInstaller/bootloader/Linux-64bit-intel/run
45194 INFO: checking EXE
45198 INFO: Building because toc changed
45198 INFO: Building EXE from EXE-00.toc
45203 INFO: Copying bootloader EXE to /home/user/install/wwrando-1.9.0/dist/Wind Waker Randomizer 1.9.0_64bit
45203 INFO: Appending PKG archive to custom ELF section in EXE
45631 INFO: Building EXE from EXE-00.toc completed successfully.
```

And the compilation succeeds. But when I ran the executable, this came out:

```
[3415] Module object for struct is NULL!
Traceback (most recent call last):
  File "struct.py", line 13, in <module>
ModuleNotFoundError: No module named '_struct'
[3415] Module object for pyimod01_archive is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod01_archive.py", line 27, in <module>
ModuleNotFoundError: No module named 'struct'
[3415] Module object for pyimod02_importers is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_importers.py", line 28, in <module>
ModuleNotFoundError: No module named 'pyimod01_archive'
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod02_importers'
[3415] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!
```

I tried to fix it by adding "struct" as a hidden import, but it didn't work.

**Comment by LagoLunatic** [comment]
Did you compile Python itself on your own or download a precompiled binary from elsewhere?

According to [this](https://stackoverflow.com/a/38781390), you must use these flags when compiling Python yourself or else PyInstaller won't work: `--enable-shared and LDFLAGS=-Wl,-rpath=<path to python lib>`

**Comment by JohnDevlopment** [comment]
Sorry for the late response. Yes, I compiled this version of Python myself. No, I did not pass those flags. It might take a few days, but I will test and see if this fixes the problem.

**Comment by JohnDevlopment** [comment]
Alright, I'm on a new system with Python 3.10.6 using the preinstalled version for Linux. I compiled the randomizer with `pysintaller` using the spec file, then ran it. I did not go further than boot up. It worked.
