### ISSUE TITLE
Randomization Failed

### ISSUE THREAD

**Issue by Gaminguy010** [LagoLunatic/wwrando#48]
I tried randomizing and got an error.

Randomization failed with error:
unpack requires a bytes object of length 4

Traceback (most recent call last):
 File "ui\randomizer_window.py", line 163, in randomize
 File "randomizer.py", line 66, in_init_
 File "randomizer.py", line 364, in get_arc
 File "wwlib\rarc.py", line 24, in_init_
 File "fs_helpers.py", line 91, in read_u32
struct.error: unpack requires a bytes object of length 4

**Comment by LagoLunatic** [comment]
You most likely have an invalid clean wind waker ISO.
Ensure your ISO's MD5 is the correct one for US wind waker: d8e4d45af2032a081a0f446384e9261b

**Comment by Gaminguy010** [comment]
Thanks for the swift response. I gotta find a new ISO.
